version: '3.7'

services:
  selfbalancingbot:
    image: gabs28/selfbalancingbot:latest
    container_name: selfbalancingbot
    privileged: true
    restart: always
    cap_add:
      - CAP_SYS_TTY_CONFIG
      - SYS_RAWIO
    volumes:
      - /dev:/dev
      - /tmp:/tmp
    devices:
      - "/dev/mem:/dev/mem"
    environment:
      REMOTE_ADDRESS: "ws://0.0.0.0:8001"
      UI_ADDRESS: "ws://0.0.0.0:8000"
    stdin_open: true
    tty: true
    pull_policy: always

  torizon-robo-demo:
    image: ghcr.io/slint-ui/slint/torizon-robo-demo-arm64-vivante:latest
    user: torizon
    volumes:
      - /run/udev:/run/udev
      - /dev:/dev
      - /tmp:/tmp
    device_cgroup_rules:
      - 'c 199:* rmw'
      - 'c 226:* rmw'
      - 'c 13:* rmw'
      - 'c 4:* rmw'
    pull_policy: always
