import { Palette } from "palette.slint";

export enum EyeState {
    Default,
    Open,
    Closed
}

export component Eye {

    private property <length> inner-height: root.height / 2;

    width: 80px;
    height: 80px;

    in property <EyeState> state: touch-area.pressed ? EyeState.Open : EyeState.Default;

    touch-area := TouchArea { }

    if root.state == EyeState.Closed : Rectangle {
        height: 1px;
        background: black;
    }

    Rectangle {
        height: root.inner-height;
        background: white;
        border-radius: root.height / 2;
        clip: true;

        Rectangle {
            width: root.width / 2.5;
            height: root.height / 2.5;
            border-radius: max(self.width, self.height) / 2;
            border-width: 1px;
            border-color: Palette.slint.darker(2.0);
            background: Palette.slint;

            Rectangle {
                width: parent.width / 2;
                height: parent.height / 2;
                border-radius: max(self.width, self.height) / 2;
                background: black;
            }
        }
    }

    states [
        closed when root.state == EyeState.Closed : {
            root.inner-height: 0px;
        }
        open when root.state == EyeState.Open : {
            root.inner-height: root.height / 1.3;
        }
    ]

    animate inner-height {
         duration: 400ms;
    }
}