import { Eye, EyeState } from "eye.slint";
import { Mouth, MouthState } from "mouth.slint";
import { Palette } from "palette.slint";

export enum FaceState {
    Happy,
    Neutral,
    Suspicious,
    Angry
}

export component Face {
    in property <FaceState> state;

    width: root.height;

    background := Rectangle {
        border-radius: max(self.width, self.height) / 2;
        border-width: 3px;
        border-color: self.background.darker(2);
        background: #fdcb47;

        left-eye := Eye {
            x: 64px;
            y: 110px;
        }

        right-eye := Eye {
            x: root.width - 64px - self.width;
            y: 110px;
        }

        mouth := Mouth {
            y: root.height / 2 + (root.height / 2 - self.height) / 2;
            width: root.width - 256px;
        }

        animate background {
             duration: 300ms;
        }
    }

    states [
        suspicious when root.state == FaceState.Suspicious : {
            left-eye.state: EyeState.PartialClosed;
            right-eye.state: EyeState.EybrownUp;
            mouth.state: MouthState.Neutral;
        }
        neutral when root.state == FaceState.Neutral : {
            mouth.state: MouthState.Neutral;
        }
        angry when root.state == FaceState.Angry : {
            left-eye.state: EyeState.PartialClosed;
            right-eye.state: EyeState.EybrownUp;
            mouth.state: MouthState.Angry;
            background.background: Palette.angy;
        }
    ]
}