import { Face, FaceState } from "face.slint";
import { ComboBox } from "std-widgets.slint";

export component MainWindow inherits Window {
    title: "robo-face";
    width: 1024px;
    height: 600px;

    Face {
        height: root.height - 64px;
        state: root.string-to-face-state(combobox.current-value);
    }

    combobox := ComboBox {
        y: 4px;

        model: [
            "Happy",
            "Neutral",
            "Suspicious",
            "Angy",
            "Bored"
        ];
    }

    pure function string-to-face-state(state: string) -> FaceState {
        if state == "Angy" {
            return FaceState.Angry;
        }

        if state == "Neutral" {
            return FaceState.Neutral;
        }

        if state == "Suspicious" {
            return FaceState.Suspicious;
        }

        if state == "Bored" {
            return FaceState.Bored;
        }

        FaceState.Happy
    }
}