export enum MouthState {
    Default,
    Closed
}

export component Mouth inherits Rectangle {
    in property <MouthState> state;

    width: 600px;
    height: root.width / 2;
    clip: true;

    Rectangle {
        y: root.height - self.height;
        width: 100%;
        height: 200%;
        border-radius: self.height / 2;
        background: black;
    }

    states [
        closed when root.state == MouthState.Closed : {
            root.height: 6px;
        }
    ]

    animate height {
        duration: 300ms;
    }
}